name: Laravel CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build containers
      run: docker compose build

    - name: Start containers
      run: docker compose up -d

    - name: Wait for containers
      run: sleep 20

    - name: Show containers
      run: docker ps -a
      
    - name: Install dependencies
      run: docker compose exec -T app composer install  

    - name: Generate key
      run: docker compose exec -T app php artisan key:generate

    - name: Run migrations
      run: docker compose exec -T app php artisan migrate