name: Laravel CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build containers
      run: docker compose build

    - name: Start containers
      run: docker compose up -d

    - name: Wait for database
      run: sleep 15

    - name: Run migrations
      run: docker compose exec -T app php artisan migrate

    - name: Test Laravel
      run: docker compose exec -T app php artisan test  